name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: [self-hosted, linux, x64]
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: "(cd tests && bash testexit.sh )"
      id: cd-tests-bash-testexit-sh
      uses: education/autograding-command-grader@v1
      with:
        test-name: "(cd tests && bash testexit.sh )"
        setup-command: ''
        command: "(cd tests && bash testexit.sh )"
        timeout: 1
        max-score: 15
    - name: runtest.sh 1
      id: runtest-sh-1
      uses: education/autograding-command-grader@v1
      with:
        test-name: runtest.sh 1
        setup-command: ''
        command: "(cd tests && bash runtest.sh 1 )"
        timeout: 2
        max-score: 10
    - name: runtest.sh 2
      id: runtest-sh-2
      uses: education/autograding-command-grader@v1
      with:
        test-name: runtest.sh 2
        setup-command: ''
        command: "(cd tests && bash runtest.sh 2 )"
        timeout: 2
        max-score: 10
    - name: runtest.sh 4
      id: runtest-sh-4
      uses: education/autograding-command-grader@v1
      with:
        test-name: runtest.sh 4
        setup-command: ''
        command: "(cd tests && bash runtest.sh 4 )"
        timeout: 2
        max-score: 9
    - name: runtest.sh 5
      id: runtest-sh-5
      uses: education/autograding-command-grader@v1
      with:
        test-name: runtest.sh 5
        setup-command: ''
        command: "(cd tests && bash runtest.sh 5 )"
        timeout: 2
        max-score: 9
    - name: runtest.sh 6
      id: runtest-sh-6
      uses: education/autograding-command-grader@v1
      with:
        test-name: runtest.sh 6
        setup-command: ''
        command: "(cd tests && bash runtest.sh 6 )"
        timeout: 2
        max-score: 9
    - name: runtest.sh 7
      id: runtest-sh-7
      uses: education/autograding-command-grader@v1
      with:
        test-name: runtest.sh 7
        setup-command: ''
        command: "(cd tests && bash runtest.sh 7 )"
        timeout: 2
        max-score: 9
    - name: runtest.sh 8
      id: runtest-sh-8
      uses: education/autograding-command-grader@v1
      with:
        test-name: runtest.sh 8
        setup-command: ''
        command: "(cd tests && bash runtest.sh 8 )"
        timeout: 2
        max-score: 9
    - name: runtest.sh 9
      id: runtest-sh-9
      uses: education/autograding-command-grader@v1
      with:
        test-name: runtest.sh 9
        setup-command: ''
        command: "(cd tests && bash runtest.sh 9 )"
        timeout: 2
        max-score: 5
    - name: test log.txt 10
      id: testlog
      uses: education/autograding-command-grader@v1
      with:
        test-name: testlog
        setup-command: ''
        command: "(cd tests && bash testlog.sh )"
        timeout: 1
        max-score: 15
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        CD-TESTS-BASH-TESTEXIT-SH_RESULTS: "${{steps.cd-tests-bash-testexit-sh.outputs.result}}"
        RUNTEST-SH-1_RESULTS: "${{steps.runtest-sh-1.outputs.result}}"
        RUNTEST-SH-2_RESULTS: "${{steps.runtest-sh-2.outputs.result}}"
        RUNTEST-SH-4_RESULTS: "${{steps.runtest-sh-4.outputs.result}}"
        RUNTEST-SH-5_RESULTS: "${{steps.runtest-sh-5.outputs.result}}"
        RUNTEST-SH-6_RESULTS: "${{steps.runtest-sh-6.outputs.result}}"
        RUNTEST-SH-7_RESULTS: "${{steps.runtest-sh-7.outputs.result}}"
        RUNTEST-SH-8_RESULTS: "${{steps.runtest-sh-8.outputs.result}}"
        RUNTEST-SH-9_RESULTS: "${{steps.runtest-sh-9.outputs.result}}"
        TESTLOG_RESULTS: "${{steps.testlog.outputs.result}}"
        
      with:
        runners: cd-tests-bash-testexit-sh,runtest-sh-1,runtest-sh-2,
                runtest-sh-4,runtest-sh-5,runtest-sh-6,runtest-sh-7,
                runtest-sh-8,runtest-sh-9,testlog